title = "Host Patrol"
baseURL = "/"
languageCode = "en-us"
disableKinds = ["taxonomy", "term"]

#####################
## SITE PARAMETERS ##
#####################

[params.media]
url = "https://media.hostpatrol.io"
ogImage = "https://media.hostpatrol.io/site/meta/og-default.png"
[params.media.logo]
default = "https://media.hostpatrol.io/site/logo.svg"
light = "https://media.hostpatrol.io/site/meta/logo-light.svg"
dark = "https://media.hostpatrol.io/site/meta/logo-dark.svg"

[params.copyright]
since = 2024
[params.copyright.owner]
name = "Vehbi Sinan Tunalioglu"
website = "https://www.thenegation.com"

[params.plausible]
domain = "hostpatrol.io"

##########
## MENU ##
##########

[menus]
[[menus.main]]
name = "Home"
title = "Home Page"
pageRef = "/"
weight = 10

[[menus.main]]
name = "Quickstart"
title = "Quickstart Guide"
pageRef = "/quickstart"
weight = 20

[[menus.main]]
name = "Console"
title = "Web-Based Console Application"
url = "https://console.hostpatrol.io"
weight = 30
[menus.main.params.anchor_attrs]
target = "_blank"
rel = "noopener"

[[menus.main]]
title = "GitHub Repository"
pre = '<img class="size-6" src="https://cdn.jsdelivr.net/npm/simple-icons@v15/icons/github.svg" alt="GitHub" />'
url = "https://github.com/vst/hostpatrol"
weight = 40
[menus.main.params.anchor_attrs]
target = "_blank"
rel = "noopener noreferrer"

#########################
## BUILD CONFIGURATION ##
#########################

[build]
[build.buildStats]
enable = true

[[build.cachebusters]]
source = 'assets/notwatching/hugo_stats\.json'
target = "css"

[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = "css"

[module]
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
disableWatch = true
source = "hugo_stats.json"
target = "assets/notwatching/hugo_stats.json"
